apiVersion: v1
kind: Service
metadata:
  name: dev-svc-repo
  namespace: dev
  labels:
    name: dev-svc-repo
    tier: serverless
spec:
  type: NodePort
  selector:
    app: dev-pod-repo
    tier: serverless
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP