apiVersion: v1
kind: Service
metadata:
  name: dev-svc-graphql
  namespace: dev
  labels:
    name: dev-svc-graphql
    tier: backend
spec:
  type: NodePort
  selector:
    app: dev-pod-graphql
    tier: backend
    version: graphql-version
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP