apiVersion: batch/v1
kind: Job
metadata:
  name: rc-job
  labels:
    name: rc-job
    type: job
spec:
  completions : 1
  parallelism: 1
  backoffLimit: 3
  template:
    spec:
      restartPolicy: onFailure
      containers:
      - name: counter-container
        image: ubuntu:latest
        command: 
          - "/bin/bash"
          - "-c"
          - for i in {1..10}; do echo "iteration $i"; done