apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-app
  template:
    metadata:
      labels:
        app: foo-app
    spec:
      containers:
        - name: foo-app
          image: robinnagpal/kubernetes-tutorial-003-node-app:latest
          env:
            - name: APP_NAME
              value: foo