apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-composition
  labels:
    name: bucket-composition
    type: composition
    project: andromeda
spec:
  compositeTypeRef:
    apiVersion: api.andromeda.org/v1
    kind: Xbucket
  resources:
    - name: s3
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        metadata:
          name: bucket-andromeda
          labels:
            name: bucket-andromeda
            type: composed-s3
            project: andromeda
        spec:
          forProvider:
            region: us-east-1
          providerConfigRef:
            name: default
