apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: Xbuckets.api.andromeda.org
  labels:
    name: Xbuckets.api.andromeda.org
    type: xrd
    project: andromeda
spec:
  group: api.andromeda.org
  names:
    kind: Xbucket
    plural: Xbuckets
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
                  oneOf:
                    - pattern: "^EU$"
                    - pattern: "^US$"
              required:
                - region
  claimNames:
    kind: bucket
    plural: buckets
