apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: istio-dr-notfound
  namespace: dev
spec:
  host: dev-svc-notfound.dev.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        connectTimeout: 10s
  subsets:
  - name: notfound-group
    labels:
      version: notfound-version