apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: dev-pod-notfound
      tier: serverless
      version: notfound-version
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            istio-injection: enabled