# kind: Role
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   namespace: jenkins
#   name: {{ .Release.Name }}-role
# rules:
#   - apiGroups: [""]
#     resources: ["pods"]
#     verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
#   - apiGroups: [""]
#     resources: ["pods/exec"]
#     verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
#   - apiGroups: [""]
#     resources: ["pods/log"]
#     verbs: ["get", "list", "watch"]
#   - apiGroups: [""]
#     resources: ["events"]
#     verbs: ["get", "list", "watch"]
#   - apiGroups: [""]
#     resources: ["secrets"]
#     verbs: ["get"]
