apiVersion: v1
kind: Service
metadata:
  name: svc-servicecall
  namespace: dev
  labels:
    app: svc-servicecall
    chartversion: {{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app: pod-servicecall
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-welcome
  namespace: dev
  labels:
    app: svc-welcome
    chartversion: {{ .Chart.Version }}
spec:
  type: ClusterIP
  selector:
    app: pod-welcome
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
