apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.NameSpace }}
  labels:
    name: {{ .Release.Name }}-svc
    tier: {{ .Values.Service.tier }}
spec:
  type: {{ .Values.Service.type }}
  selector:
    app: {{ .Release.Name }}-pod
    tier: {{ .Values.Deployment.pod.tier }}
    version: {{ .Values.Deployment.pod.version }}
  ports:
    - port: {{ .Values.Service.ports.port }}
      targetPort: {{ .Values.Service.ports.targetPort }}
      protocol: {{ .Values.Service.ports.protocol }}