apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.NameSpace.name }}
  labels:
    name: {{ .Release.Name }}-svc
    tier: {{ .Values.Service.tier }}
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  type: {{ .Values.Service.type }}
  selector:
{{- include "andromeda.charts.pod.label" . | indent 4 }}
  ports:
    - port: {{ .Values.Service.ports.port }}
      targetPort: {{ .Values.Service.ports.targetPort }}
      protocol: {{ .Values.Service.ports.protocol }}