apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrepositorys.api.andromeda.org
  labels:
    name: xrepositorys.api.andromeda.org
    type: xrd
    project: andromeda
spec:
  group: api.andromeda.org
  names:
    kind: XRepository
    plural: xrepositorys
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                region:
                  type: string
                tags:
                  type: object
                  project:
                    type: string
                  resource_type:
                    type: string
              required:
                - region
                - tags
  claimNames:
    kind: Repository
    plural: repositorys
