apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  labels:
    name: prometheus-service
    tier: monitoring
spec:
  selector:
    app: prometheus-pod
    tier: monitoring
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP