apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-depl
  namespace: jenkins
  labels:
    name: {{ .Release.Name }}-depl
    tier: integration
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-pod
      tier: integration
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-pod
        tier: integration
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}
