apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-volume
  namespace: jenkins
  labels:
    purpose: {{ .Release.Name }}-volume
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jenkins/data"
