apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "node-exporter"
    app: prometheus
    release: testchart
    chart: prometheus-13.2.1
    heritage: Helm
  name: testchart-prometheus-node-exporter
  namespace: default
  annotations:
    {}