apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-helloworld
  namespace: dev
  labels:
    name: hpa-helloworld
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: depl-helloworld
  minReplicas: 1
  maxReplicas: 3
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 20
      policies:
        - type: Percent
          value: 10
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 20
      policies:
        - type: Percent
          value: 10
          periodSeconds: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
