apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-network-policy
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  ingress:
  - ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443