apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-pod
    tier: integration
  ports:
    - name: jenkins-port
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: slave
      port: 5000
      targetPort: 5000
      protocol: TCP
