apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: jenkins-master
      protocol: TCP
    - port: 50000
      targetPort: 50000
      name: jenkins-jnlp
      protocol: TCP
  selector:
    name: {{ .Release.Name }}-pod
    tier: integration
