apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.NameSpace }}
type: {{ .Values.Secrets.type }}
data:
   DEV_MONGODB_USERNAME: YWRtaW4K
   DEV_MONGODB_PASSWORD: YWRtaW4K
   DEV_MONGODB_HOST: Y2x1c3Rlci1hbmRyb21lZGEubXMwOWwubW9uZ29kYi5uZXQK
   DEV_MONGODB_DATABASE: QW5kcm9tZWQK
   DEV_MONGODB_RETRYWRITES: dHJ1ZQo=
   DEV_MONGODB_WRITECONCERN: bWFqb3JpdHkK
   DEV_POSTGRESQL_PGUSER: cG9zdGdyZXMK
   DEV_POSTGRESQL_PGPASSWORD: YWRtaW4K
   DEV_POSTGRESQL_PGDATABASE: cG9zdGdyZXMK
   DEV_POSTGRESQL_PGPORT: NTQzMgo=
   DEV_POSTGRESQL_PGHOST: bG9jYWxob3N0Cg==
   DEV_GRAPHQL_ENCRYPTION_KEY: ZVRoV21acTR0N3dDJkYpSkBOY1JmVWpYbjJyNXUK