apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.NameSpace.name }}
  annotations:
{{- include "andromeda.charts.annotations.stage2" . | indent 4 }}
type: {{ .Values.Secrets.type }}
data:
{{- include "andromeda.charts.secrets.data" . | indent 4 }}