apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-2.9.7
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: testchart
  name: testchart-kube-state-metrics
rules:
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests
    verbs: ["list", "watch"]

  - apiGroups: [""]
    resources:
      - configmaps
      - limitranges
      - persistentvolumeclaims
      - persistentvolumes
      - replicationcontrollers
      - resourcequotas
      - secrets
      - namespaces
      - endpoints
      - services
      - nodes
      - nodes/proxy
      - nodes/metrics
      - pods
    verbs: ["list", "watch", "get"]

  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["list", "watch"]

  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["list", "watch"]

  - apiGroups: ["extensions", "networking.k8s.io", "apps"]
    resources:
      - ingresses
      - replicasets
      - deployments
      - daemonsets
      - networkpolicies
      - statefulsets
    verbs: ["list", "watch"]

  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["list", "watch"]

  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["list", "watch"]

  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
    verbs: ["list", "watch"]

  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
      - subjectaccessreviews
    verbs: ["list", "watch", "create"]

  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
