apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    component: "pushgateway"
    app: prometheus
    release: testchart
    chart: prometheus-13.2.1
    heritage: Helm
  name: testchart-prometheus-pushgateway
rules:
  []