apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: jenkins
  labels:
    name: {{ .Release.Name }}-configmap
    tier: integration
data:
  JENKINS_USERNAME: admin
  JENKINS_PASSWORD: admin
