apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: istio-dr-graphql
  namespace: dev
spec:
  host: dev-svc-graphql.dev.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        connectTimeout: 20s
      http:
        idleTimeout: 30s
      outlierDetection:
        interval: 12s
  subsets:
  - name: graphql-group
    labels:
      version: graphql-version