apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: istio-dr-graphql
  namespace: dev
spec:
  host: dev-svc-graphql.dev.svc.cluster.local
  trafficPolicy: ~
  subsets:
  - name: graphql-group
    labels:
      version: graphql-version