apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: istio-dr-graphql
  namespace: dev
spec:
  host: dev-svc-graphql.dev.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        connectTimeout: 10s
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: graphql-group
      labels:
        version: graphql-version
