apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: dev
  labels:
    app: prometheus-deployment
    tier: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pod
      tier: monitoring
  template:
    metadata:
      labels:
        app: prometheus-pod
        tier: monitoring
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - name: prometheus-port
              containerPort: 9090
              protocol: TCP

          startupProbe:
            httpGet:
              path: /
              port: prometheus-port
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
                      
          readinessProbe:
            httpGet:
              path: /
              port: prometheus-port
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: prometheus-port
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 0777
            name: prometheus-conf
        - name: prometheus-storage-volume
          emptyDir: {}