apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pgadmin-configmap
  labels:
    name: {{ .Release.Name }}-pgadmin-configmap
    tier: weba
data:
  PGADMIN_DEFAULT_EMAIL: test
  PGADMIN_DEFAULT_PASSWORD: password