apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    component: "node-exporter"
    app: prometheus
    release: testchart
    chart: prometheus-13.2.1
    heritage: Helm
  name: testchart-prometheus-node-exporter
  namespace: dev
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    component: "node-exporter"
    app: prometheus
    release: testchart
  type: "ClusterIP"
