apiVersion: v1
kind: Secret
metadata:
  name: dev-secret-graphql
  namespace: dev
type: Opaque
data:
   USERNAME: YWRtaW4K
   PASSWORD: YWRtaW4K
   HOST: Y2x1c3Rlci1hbmRyb21lZGEubXMwOWwubW9uZ29kYi5uZXQK
   DATABASE: QW5kcm9tZWQK
   RETRYWRITES: dHJ1ZQo=
   WRITECONCERN: bWFqb3JpdHkK