apiVersion: v1
kind: Secret
metadata:
  name: dev-secret-graphql
  namespace: dev
type: Opaque
data:
   DEV_MONGODB_USERNAME: YWRtaW4K
   DEV_MONGODB_PASSWORD: YWRtaW4K
   DEV_MONGODB_HOST: Y2x1c3Rlci1hbmRyb21lZGEubXMwOWwubW9uZ29kYi5uZXQK
   DEV_MONGODB_DATABASE: QW5kcm9tZWQK
   DEV_MONGODB_RETRYWRITES: dHJ1ZQo=
   DEV_MONGODB_WRITECONCERN: bWFqb3JpdHkK