apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-express
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: aputrabay/express:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: testapp-port
          containerPort: 8080
        securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi