apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-ingress-listener-8080
spec:
  port: 3000
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL