apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-service
    tier: alertmanager
  name: prometheus-service
  namespace: dev
spec:
  ports:
    - name: http
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: prometheus-pod
    tier: alertmanager
  sessionAffinity: None
  type: ClusterIP