apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: dev-pdf-notfound
  namespace: dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dev-pod-notfound
      tier: serverless
      version: notfound-version
