apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress-graphql
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-svc-graphql
            port:
              number: 8000