apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  labels:
    name: default
    type: provider-conf
    project: andromeda
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds
