apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-clusterrolebinding
  labels:
    name: dev-clusterrolebinding
    type: clusterrolebinding
subjects:
  - kind: Group
    name: "testgroup"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dev-clusterrole
  apiGroup: rbac.authorization.k8s.io
