apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: dev-rolebinding
  labels:
    name: dev-rolebinding
    type: rolebinding
subjects:
  - kind: Group
    name: "testgroup"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io
