apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ .Release.Name }}-configmap
 namespace: {{ .Values.NameSpace.name }}
 labels:
    name: {{ .Release.Name }}-configmap
    tier: {{ .Values.ConfigMap.tier }}
data:
{{- include "andromeda.charts.configmap.data" . | indent 2 }}