apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin-service
  labels:
    name: {{ .Release.Name }}-pgadmin-service
    tier: web
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    name: {{ .Release.Name }}-pgadmin-pod
    tier: web
