apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: dev-pdf-repo
  namespace: dev
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: dev-pod-repo
      tier: serverless
      version: repo-version
